platform :ios, '13.4'

prepare_react_native_project!

target 'risebysolis' do
  config = use_native_modules!

  # Flags to enable extra React Native features
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true
  )

  # Explicitly merge the single post_install configuration block
  post_install do |installer|
    react_native_post_install(installer) if respond_to?(:react_native_post_install)
    __apply_Xcode_12_and_greater_settings(installer) if respond_to?(:__apply_Xcode_12_and_greater_settings)

    # Force the broken 'fmt' library to compile using standard C++17 rules
    installer.pods_project.targets.each do |target|
      if target.name == 'fmt'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        end
      end
    end
  end

end
